### ISSUE TITLE
login md

### ISSUE THREAD

**Issue by ricardorohde** [crbonilha/utfpr-login#4]
Opa, 
não quer me ajudar a fazer algo pro materdei?

**Comment by crbonilha** [comment]
olá.
materdei? do que se trata?

**Comment by ricardorohde** [comment]
la tb tem hotpot pra login com ra e senha.
sera q tem como fazer semelhante

**Comment by crbonilha** [comment]
não seria difícil adaptar esse código para funcionar lá, eu acho.
talvez seja até mais interessante fazer uma extensão que seja configurável para qualquer hotspot.

**Comment by ricardorohde** [comment]
o q preciso te mandar pra vc ver

**Comment by crbonilha** [comment]
salva a página de login pra eu ver se vai ser fácil.
basta apertar Ctrl+S.

**Comment by pedroguilhermelima** [comment]
Olá, pessoal!

Essa é a minha ideia de uma nova interface gráfica. Estive pensando em ajudar, mas não sei se vão gostar. Então, mostrarei o screenshot desta ideia - a nova interface gráfica. 

![desktop](https://user-images.githubusercontent.com/46846354/54506762-d8663680-491c-11e9-81b6-8cd9b9e0ec86.png)
